export const SUPPORTED_CURRENCIES = [
  "USD", "EUR", "GBP", "JPY", "AUD", "CAD", "CHF", "CNY", "SEK", "NZD",
  "MXN", "SGD", "HKD", "NOK", "TRY", "ZAR", "BRL", "INR", "KRW", "PLN",
  "DKK", "CZK", "HUF", "RUB", "THB", "ILS", "CLP", "PHP", "AED", "SAR",
  "LKR",
] as const;

export const CRYPTO_CURRENCIES = ["BTC", "ETH", "LTC"] as const;

export const CURRENCY_NAMES: Record<string, string> = {
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  SEK: "Swedish Krona",
  NZD: "New Zealand Dollar",
  MXN: "Mexican Peso",
  SGD: "Singapore Dollar",
  HKD: "Hong Kong Dollar",
  NOK: "Norwegian Krone",
  TRY: "Turkish Lira",
  ZAR: "South African Rand",
  BRL: "Brazilian Real",
  INR: "Indian Rupee",
  KRW: "South Korean Won",
  PLN: "Polish Zloty",
  DKK: "Danish Krone",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  RUB: "Russian Ruble",
  THB: "Thai Baht",
  ILS: "Israeli Shekel",
  CLP: "Chilean Peso",
  PHP: "Philippine Peso",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  LKR: "Sri Lankan Rupee",
};

export const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  AUD: "A$",
  CAD: "C$",
  CHF: "Fr",
  CNY: "¥",
  SEK: "kr",
  NZD: "NZ$",
  MXN: "$",
  SGD: "S$",
  HKD: "HK$",
  NOK: "kr",
  TRY: "₺",
  ZAR: "R",
  BRL: "R$",
  INR: "₹",
  KRW: "₩",
  PLN: "zł",
  DKK: "kr",
  CZK: "Kč",
  HUF: "Ft",
  RUB: "₽",
  THB: "฿",
  ILS: "₪",
  CLP: "$",
  PHP: "₱",
  AED: "د.إ",
  SAR: "﷼",
  LKR: "Rs",
};

export const CURRENCY_REGIONS: Record<string, string> = {
  USD: "North America",
  CAD: "North America",
  MXN: "North America",
  EUR: "Europe",
  GBP: "Europe",
  CHF: "Europe",
  SEK: "Europe",
  NOK: "Europe",
  DKK: "Europe",
  CZK: "Europe",
  HUF: "Europe",
  PLN: "Europe",
  RUB: "Europe",
  JPY: "Asia",
  CNY: "Asia",
  KRW: "Asia",
  SGD: "Asia",
  HKD: "Asia",
  THB: "Asia",
  INR: "Asia",
  PHP: "Asia",
  AUD: "Oceania",
  NZD: "Oceania",
  BRL: "South America",
  CLP: "South America",
  ZAR: "Africa",
  AED: "Middle East",
  SAR: "Middle East",
  ILS: "Middle East",
  TRY: "Middle East",
  LKR: "Asia",
};

export const DEFAULT_CURRENCY = "USD";
