export enum LoyaltyTier {
  STYLE_LOVER = 'STYLE_LOVER',
  FASHION_FAN = 'FASHION_FAN',
  STYLE_INSIDER = 'STYLE_INSIDER',
  VIP_STYLIST = 'VIP_STYLIST',
}

export enum LoyaltyTransactionType {
  EARN = 'EARN',
  REDEEM = 'REDEEM',
  EXPIRE = 'EXPIRE',
  ADJUST = 'ADJUST',
}

export enum LoyaltyTransactionReason {
  PURCHASE = 'PURCHASE',
  SIGNUP = 'SIGNUP',
  REVIEW = 'REVIEW',
  STYLE_QUIZ = 'STYLE_QUIZ',
  OUTFIT_PHOTO = 'OUTFIT_PHOTO',
  SOCIAL_SHARE = 'SOCIAL_SHARE',
  BIRTHDAY = 'BIRTHDAY',
  REFERRAL = 'REFERRAL',
  GOODWILL = 'GOODWILL',
  REFUND = 'REFUND',
  DISCOUNT_REDEMPTION = 'DISCOUNT_REDEMPTION',
  PRODUCT_REDEMPTION = 'PRODUCT_REDEMPTION',
  EXPIRY = 'EXPIRY',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}
